language: rust
cache: cargo
rust:
  - 1.40.0
  - stable
  - beta
jobs:
  include:
    - rust: 1.40.0
      env: TEST_MINIMAL_VERSIONS=1
    - rust: 1.40.0
      env: LINT=1
before_install:
  - |
    if [ "${LINT:-0}" -ne 0 ] ; then
        rustup component add clippy rustfmt
        cargo clippy --version
        cargo fmt --version
    fi
  - |
    if [ "${TEST_MINIMAL_VERSIONS:-0}" -ne 0 ] ; then
        rustup install nightly
    fi
before_script:
  # Use dependencies with minimal versions.
  - |
    if [ "${TEST_MINIMAL_VERSIONS:-0}" -ne 0 ] ; then
        cargo +nightly update -Z minimal-versions
    fi
script:
  - if [ "${LINT:-0}" -eq 0 ] ; then cargo build --verbose --workspace --all-features && cargo test --verbose --workspace --all-features ; fi
  # Fail if the code is correctly formatted.
  - if [ "${LINT:-0}" -ne 0 ] ; then cargo fmt --all -- --check ; fi
  # Fail if the code has warnings.
  - if [ "${LINT:-0}" -ne 0 ] ; then cargo clippy --all-features -- --deny warnings ; fi
notifications:
  email: false
